spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: postgres
server:
  servlet:
    context-path: /ex-beginner
logging:
  level:
    '[org.springframework.jdbc.core]': debug
    '[com.example.exbeginner]': debug
