spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://localhost:5432/student
    username: postgres
    password: postgres
server:
  servlet:
    context-path: /ex-beginner
